### ISSUE TITLE
Rotate Y label to -90 deg when yOrient is 'left'

### ISSUE THREAD

**Issue by mbssantos** [d3fc/d3fc-chart#9]
Labels are rotated 90deg instead of the usual -90deg

**Comment by chrisprice** [comment]
Alternatively always rotate -90deg, it fits with how westerners read (i.e. T2B, L2R)

**Comment by ColinEberhardt** [comment]
> Alternatively always rotate -90deg, it fits with how westerners read (i.e. T2B, L2R)

Nice idea! @mbssantos feel free to contribute a fix if you like?
